backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "team"
    label: "Team Members"
    folder: "data/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}

  - name: "testimonials"
    label: "Testimonials"
    folder: "data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
